updated ssmcc and ssmcc.asm; changed `pop cx' to `pop ax' near the beginning of _cstart_

diff --git a/ssmcc b/ssmcc
--- a/ssmcc
+++ b/ssmcc
@@ -5,8 +5,8 @@
 #
 # Quick try (run the commands on Linux i386 or amd64, without the leading `$`):
 #
-#   $ owcc  # Check that it's properly installed.
-#   $ echo 'int main() { return write(1, "Hello, World\n", 14) == 14; }' >hw.c
+#   $ owcc  # Check that OpenWatcom v2 is properly installed.
+#   $ echo 'int main() { return write(1, "Hello, World!\n", 14) != 14; }' >hw.c
 #   $ ./ssmcc -bminix -Os -Wno-n131 -o hw hw.c
 #   $ ls -l hw
 #
@@ -42,16 +42,26 @@ unset WATCOM  # Don't let the OpenWatcom v2 linker (WLINK) find its own config f
 case "$1" in
  -belks) cdefs="-D__ELKS__ -D__ELKS -D__elks__ -D__elks -D__unix__"; wasmdefs="-Wc,-d__ELKS__"; shift ;;  # Dev86 has -D__ELKS__ -D__unix__.
  -bminix | -bminixi86) cdefs="-D__MINIX__ -D__MINIX -D__minix__ -D__minix -D__unix__"; wasmdefs="-Wc,-d__MINIX__"; shift ;;  # The ACK ANSI C compiler 1.202 on Minix >=1.7.0 has -D__MINIX. The non-ANSI ACK 3.1 C compiler on Minix 1.5.10 doesn't have anything.
- *) echo "fatal: please specify -bminix or -belks first" >&2; exit 2 ;;
+ *) echo "fatal: please specify -bminix or -belks first" >&2; exit 3 ;;
 esac
 cdefs="-D__SSMCC__ -D__SIZEOF_INT__=2 -D__SIZEOF_LONG__=4 -D__SIZEOF_POINTER__=2 $cdefs"; wasmdefs="-Wc,-d__SSMCC__ $wasmdefs"
 
-## Figure out the output executable program filename ($ofn) from the command-line arguments ("$@").
-next=
+## Figure out the system include directory.
+if test -f "$ssmccdir/include/stddef.h"; then sysinc="$ssmccdir/include"
+elif test -d "$ssmccdir/../ssmccinclude/stddef.h"; then sysinc="$ssmccdir/../ssmccinclude"
+else echo "fatal: ssmcc system include directory not found near: $ssmccdir" >&2; exit 4
+fi
+export INCLUDE="$sysinc"  # Respected by OpenWatcom v2 C compiler (wcc) called by owcc.
+
+## Figure out the output executable program filename ($ofn) from the command-line arguments ("$@"), and whether we are linking.
+next=; dolink=1
 for arg in "$@"; do
   case "$next" in o) ofn="$arg"; next= ;; esac
-  case "$arg" in -o) next=o ;; -o*) ofn="${arg#??}" ;; esac
+  case "$arg" in -o) next=o ;; -o*) ofn="${arg#??}" ;; -[EcS]) dolink=0 ;; esac
 done
+
+## If not linking, then just run the compiler driver owcc.
+case "$dolink" in 0) owcc -bbegin -march=i86 -fno-stack-check -mcmodel=s -mabi=cdecl -fnostdlib -fsigned-char $cdefs "$@"; exit "$?" ;; esac
 case "$ofn" in "") ofn=a.out; set x -o "$ofn" "$@"; shift ;; esac
 
 ## Compile the program using the OpenWatcom v2 C compiler (wcc) started by the OpenWatcom v2 C compiler Unix driver (owcc).
@@ -60,13 +70,14 @@ owcc -bbegin -march=i86 -Wl,x -Wl,end -Wl,form -Wl,dos -fno-stack-check -mcmodel
 # Compile a list of undefined symbols. Example: undefs="-Wc,-dU_cstart_ -Wc,-dU_write -Wc,-dU__argc"
 undefs="$(perl -e 'my $xc = 77; my @s; while (<STDIN>) { if (m@^Error! E[^:]+: (\S+) is an undefined reference$@) { push(@s, "-Wc,-dU$1"); $xc = 0 } } print("@s\n"); exit($xc)' <ssmcc.err)"; xcu="$?"
 case "$xcu" in
- 77) perl -pe "" <ssmcc.err >&2; rm -f ssmcc.err; exit 3 ;;  # No undefined symbols found, so there must be some other owcc error. `cat' would also work instead of (and would be faster than) `perl -pe ""', but that would be 1 extra external command dependency.
+ 77) perl -pe "" <ssmcc.err >&2; rm -f ssmcc.err; exit 5 ;;  # No undefined symbols found, so there must be some other owcc error. `cat' would also work instead of (and would be faster than) `perl -pe ""', but that would be 1 extra external command dependency.
  0) rm -f ssmcc.err ;;  # Found some undefined symbols, saved them to $undefs.
- *) rm -f ssmcc.err; echo "fatal: error running Perl to find the libc functions used" >&2; exit 4 ;;
+ *) rm -f ssmcc.err; echo "fatal: error running Perl to find the libc functions used" >&2; exit 6 ;;
 esac
 rm -f ssmcc.err
 owcc -bdos -s -mcmodel=s -c $wasmdefs $undefs -o ssmcc.o "$ssmccdir"/ssmcc.asm || exit "$?"
 # ssmcc.o must be specified first, because $edata is expected right after the DOS MZ .exe header, i.e. at the beginning of _TEXT.
+# TODO(pts): size optimization: Reuse the .o files created in the run of owcc above.
 owcc -bbegin -march=i86 -Wl,x -Wl,end -Wl,form -Wl,dos -fno-stack-check -mcmodel=s -mabi=cdecl -fnostdlib -fsigned-char -Wl,op -Wl,stack=1 -Wl,disable -Wl,1172 -s $cdefs ssmcc.o "$@" || exit "$?"
 rm -f ssmcc.o
 
@@ -87,13 +98,14 @@ perl -we 'use integer; use strict;
     my $a_unused = 0;  # Must be 0 for Minix.
     my $a_version = 0;  # Must be 0 for Minix.
     my $a_text = ((($size + 1) & ~1) - 0x20) - $edata;
-    my $a_data = $edata;
-    my $a_bss = (($ss << 4 | $sp) - 1) - ((($size + 1) & ~1) - 0x20);  # -1 is because of `wlink op stack=1`.
+    my $a_data = $edata - (-$size & 1);
+    my $a_bss = (($ss << 4 | $sp) - 1) - ($size - 0x20);  # -1 is because of `wlink op stack=1`.
     my $a_entry = 0;  # Must be 0 for Minix 1.5.10.
     my $a_total = 0x10000;  # Typical to maximize the data segment.
     my $a_syms = 0;  # Exeutable stripped.
-    my $instr2 = "\xfc\x59";  # Put `cld ++ push cx` back to the beginning of _cstart_.
+    my $instr2 = "\xfc\x58";  # Put `cld ++ pop ax` back to the beginning of _cstart_.
     $_ = pack("a2CCCCvV6a2", $a_magic, $a_flags, $a_cpu, $a_hdrlen, $a_unused, $a_version, $a_text, $a_data, $a_bss, $a_entry, $a_total, $a_syms, $instr2);
     die("fatal: error writing header: $fn\n") if (syswrite(F, $_, 0x22) or 0) != 0x22;
+    # TODO(pts): Remove the trailing NUL bytes at the end of .text, make $a_text smaller.
     ' "$ofn" || exit "$?"
 # chmod +x -- "$ofn"  # Not needed, owcc makes it executable on Linux.
